- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update system (apt)
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Install base packages (apt)
      loop:
        - build-essential
        - git
        - curl
        - unzip
        - tar
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      when: ansible_distribution == "Ubuntu"

    - name: Test stow
      shell: "stow i3 -d {{ ansible_env.HOME }}/dotfiles --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
