- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update system (apt)
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Install base packages (apt)
      loop:
        - build-essential
        - git
        - curl
        - unzip
        - tar
        - zsh
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      when: ansible_distribution == "Ubuntu"

    - name: Create directories
      loop:
        - "{{ ansible_env.HOME }}/.config"
        - "{{ ansible_env.HOME }}/opt"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Stow Dotfiles
      loop:
        - nvim
        - i3
      shell: "stow {{ item }} -d {{ ansible_env.HOME }}/dotfiles --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'

    # Add ZSH And oh my zsh
    - name: Testing
      debug:
        var: "{{ ansible_env.USER }}"

    - name: Download NVIM
      ansible.builtin.get_url:
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz
        dest: "{{ ansible_env.HOME }}/opt"
        checksum: sha256:https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.tar.gz.sha256sum
      register: download_nvim

    - name: Unpack NVIM
      unarchive:
        src: "{{ download_nvim.dest }}"
        dest: "{{ ansible_env.HOME }}/opt"
      when: download_nvim.changed == true
