- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update repos
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    - name: Install htop
      apt:
        name: htop
