- hosts: localhost
  connection: local

  pre_tasks:
    - name: Update system (apt)
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Install base packages (apt)
      loop:
        - build-essential
        - git
        - curl
        - unzip
        - tar
      apt:
        name: "{{ item }}"
        state: present
      become: yes
      when: ansible_distribution == "Ubuntu"

    - name: Create directories
      loop:
        - "{{ ansible_env.HOME }}/.config"
        - "{{ ansible_env.HOME }}/opt"
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory

    - name: Stow i3 Config
      shell: "stow i3 -d {{ ansible_env.HOME }}/dotfiles --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'

    - name: Stow Neovim config
      shell: "stow nvim -d {{ ansible_env.HOME }}/dotfiles --target {{ ansible_env.HOME }} --verbose=2"
      register: result
      changed_when: 'result.stderr is search("LINK: ")'
