- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Update system (apt)
      apt:
        update_cache: yes
        upgrade: yes
      become: yes
      when: ansible_distribution == "Ubuntu"

  tasks:
    - name: Install base packages (apt)
      apt:
        name:
          - build-essential
          - git
          - curl
          - unzip
        state: present
      become: yes
      when: ansible_distribution == "Ubuntu"
